services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tochka
      - ADMIN_TOKEN=qyLFpbXdjCflyuWZ3TvXESo7jNOBNIy
    ports:
      - 8000:8000

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tochka

volumes:
  postgres_data:

